"use strict";

const { contrastForeground, darken, lighten, mix } = require("./colors");
const { createSemanticTokens } = require("./semantic-tokens");

function generateThemeJson(entry) {
  const { slug, name, colors, levels, ui, light, hc } = entry;
  const {
    accentForeground,
    frameBackground,
    isDark,
    selection,
    selectionInactive,
    transparent,
  } = createSemanticTokens(entry);

  // Map VS Code token colors to IntelliJ editor scheme attributes
  const theme = {
    name: name,
    dark: isDark,
    parentTheme: isDark ? "Islands Dark" : "Islands Light",
    author: "Bearded Bear (IntelliJ port)",
    editorScheme: `/themes/${slug}.xml`,
    ui: {
      // IntelliJ 2025.3+ Islands layout metrics.
      Islands: 1,
      "Island.arc": 20,
      "Island.arc.compact": 16,
      "Island.borderWidth": 5,
      "Island.borderWidth.compact": 4,
      "Island.borderColor": ui.uibackground,
      "Island.inactiveAlpha": 0.44,
      "*": {
        arc: isDark ? 10 : 8,
        background: ui.uibackground,
        foreground: ui.font,
        selectionBackground: selection,
        selectionForeground: ui.font,
        selectionInactiveBackground: selectionInactive,
        disabledBackground: ui.uibackgroundalt,
        disabledForeground: ui.fontalt,
        disabledText: ui.fontalt,
        errorForeground: levels.danger,
        infoForeground: levels.info,
        lightSelectionBackground: isDark ? lighten(ui.uibackground, 10) : darken(ui.uibackground, 10),
        separatorColor: ui.border,
      },
      ActionButton: {
        hoverBackground: ui.defaultalt,
        hoverBorderColor: ui.defaultalt,
        pressedBackground: isDark ? lighten(ui.defaultalt, 5) : darken(ui.defaultalt, 5),
        pressedBorderColor: ui.border,
      },
      Button: {
        arc: 10,
        default: {
          foreground: accentForeground,
          startBackground: ui.primary,
          endBackground: ui.primary,
          startBorderColor: ui.primary,
          endBorderColor: ui.primary,
          focusedBorderColor: lighten(ui.primary, 10),
        },
        foreground: ui.font,
        startBackground: ui.defaultalt,
        endBackground: ui.defaultalt,
        startBorderColor: ui.border,
        endBorderColor: ui.border,
        shadowColor: darken(ui.uibackground, 5),
      },
      CheckBox: {
        background: ui.uibackground,
        foreground: ui.font,
      },
      ComboBox: {
        arc: 10,
        background: ui.uibackgroundalt,
        foreground: ui.font,
        selectionBackground: ui.primary,
        selectionForeground: accentForeground,
        nonEditableBackground: ui.uibackgroundalt,
        ArrowButton: {
          background: ui.uibackgroundalt,
          nonEditableBackground: ui.uibackgroundalt,
          iconColor: ui.fontalt,
        },
      },
      CompletionPopup: {
        background: ui.uibackground,
        foreground: ui.font,
        matchForeground: ui.primary,
        selectionBackground: ui.defaultalt,
        selectionInactiveBackground: ui.default,
      },
      Counter: {
        background: ui.primary,
        foreground: accentForeground,
      },
      DefaultTabs: {
        background: ui.uibackground,
        underlineColor: ui.primary,
        inactiveUnderlineColor: ui.fontalt,
        hoverBackground: ui.defaultalt,
        underlinedTabBackground: isDark ? lighten(ui.uibackground, 3) : darken(ui.uibackground, 3),
        underlinedTabForeground: ui.font,
        underlineHeight: 3,
      },
      DragAndDrop: {
        areaBackground: isDark ? lighten(ui.uibackground, 8) + "80" : darken(ui.uibackground, 8) + "80",
        borderColor: ui.primary,
      },
      Editor: {
        background: ui.uibackground,
        foreground: ui.font,
        shortcutForeground: ui.primary,
      },
      EditorTabs: {
        // Islands tabs sit on the editor surface and use a filled selected tab.
        background: ui.uibackground,
        underlineColor: ui.primary,
        underlinedBorderColor: ui.primary,
        inactiveUnderlinedTabBorderColor: ui.border,
        underlineHeight: 2,
        underlinedTabBackground: ui.defaultalt,
        inactiveUnderlinedTabBackground: ui.default,
        underlinedTabForeground: ui.font,
        inactiveUnderlineColor: "transparent",
        inactiveMaskColor: "#00000000",
      },
      FileColor: {
        Yellow: isDark ? lighten(ui.uibackground, 3) : darken(ui.uibackground, 3),
        Green: isDark ? mix(ui.uibackground, levels.success, 0.9) : mix(ui.uibackground, levels.success, 0.9),
        Blue: isDark ? mix(ui.uibackground, levels.info, 0.9) : mix(ui.uibackground, levels.info, 0.9),
        Violet: isDark ? mix(ui.uibackground, colors.purple, 0.9) : mix(ui.uibackground, colors.purple, 0.9),
        Orange: isDark ? mix(ui.uibackground, levels.warning, 0.9) : mix(ui.uibackground, levels.warning, 0.9),
        Rose: isDark ? mix(ui.uibackground, levels.danger, 0.9) : mix(ui.uibackground, levels.danger, 0.9),
      },
      Link: {
        activeForeground: ui.primary,
        hoverForeground: lighten(ui.primary, 10),
        pressedForeground: darken(ui.primary, 10),
        visitedForeground: colors.purple,
        secondaryForeground: ui.fontalt,
      },
      List: {
        background: ui.uibackground,
        foreground: ui.font,
        selectionBackground: ui.defaultalt,
        selectionForeground: ui.font,
        selectionInactiveBackground: ui.default,
        selectionInactiveForeground: ui.font,
        hoverBackground: ui.default,
        hoverInactiveBackground: ui.default,
      },
      Menu: {
        background: ui.uibackground,
        foreground: ui.font,
        selectionBackground: ui.defaultalt,
        selectionForeground: ui.font,
        separatorColor: ui.border,
        borderColor: ui.border,
      },
      MenuBar: {
        background: frameBackground,
        foreground: ui.font,
        hoverBackground: ui.defaultalt,
        selectionBackground: ui.defaultalt,
        selectionForeground: ui.font,
      },
      NavBar: {
        borderColor: ui.border,
      },
      MainToolbar: {
        background: frameBackground,
        borderColor: transparent,
      },
      MainWindow: {
        background: frameBackground,
      },
      Notification: {
        background: ui.uibackgroundalt,
        foreground: ui.font,
        borderColor: ui.border,
        errorBackground: mix(ui.uibackground, levels.danger, 0.8),
        errorForeground: ui.font,
        errorBorderColor: levels.danger,
        ToolWindow: {
          informativeBackground: ui.uibackgroundalt,
          informativeForeground: ui.font,
          informativeBorderColor: levels.info,
          warningBackground: mix(ui.uibackground, levels.warning, 0.8),
          warningForeground: ui.font,
          warningBorderColor: levels.warning,
          errorBackground: mix(ui.uibackground, levels.danger, 0.8),
          errorForeground: ui.font,
          errorBorderColor: levels.danger,
        },
      },
      Panel: {
        background: ui.uibackground,
        foreground: ui.font,
      },
      Plugins: {
        background: ui.uibackground,
        SearchField: {
          background: ui.uibackgroundalt,
        },
        SectionHeader: {
          background: ui.uibackgroundalt,
          foreground: ui.font,
        },
        hoverBackground: ui.default,
        lightSelectionBackground: ui.defaultalt,
        tagBackground: ui.defaultalt,
        tagForeground: ui.font,
        Button: {
          installBackground: ui.primary,
          installForeground: accentForeground,
          installBorderColor: ui.primary,
          installFillBackground: ui.primary,
          installFillForeground: accentForeground,
          updateBackground: levels.info,
          updateForeground: contrastForeground(levels.info),
          updateBorderColor: levels.info,
        },
      },
      Popup: {
        arc: 12,
        background: ui.uibackground,
        foreground: ui.font,
        Header: {
          activeBackground: ui.defaultalt,
          inactiveBackground: ui.default,
        },
        Advertiser: {
          background: ui.uibackgroundalt,
          foreground: ui.fontalt,
          borderColor: ui.border,
        },
        borderColor: ui.border,
        inactiveBorderColor: ui.border,
        separatorColor: ui.border,
        separatorForeground: ui.fontalt,
        paintBorder: true,
      },
      ProgressBar: {
        progressColor: ui.primary,
        indeterminateStartColor: ui.primary,
        indeterminateEndColor: lighten(ui.primary, 20),
        trackColor: ui.defaultalt,
        failedColor: levels.danger,
        failedEndColor: darken(levels.danger, 10),
        passedColor: levels.success,
        passedEndColor: lighten(levels.success, 10),
      },
      ScrollBar: {
        Mac: {
          thumbColor: isDark ? lighten(ui.uibackground, 15) + "80" : darken(ui.uibackground, 15) + "80",
          thumbBorderColor: isDark ? lighten(ui.uibackground, 15) + "80" : darken(ui.uibackground, 15) + "80",
          hoverThumbColor: isDark ? lighten(ui.uibackground, 25) + "B0" : darken(ui.uibackground, 25) + "B0",
          hoverThumbBorderColor: isDark ? lighten(ui.uibackground, 25) + "B0" : darken(ui.uibackground, 25) + "B0",
          Transparent: {
            thumbColor: isDark ? lighten(ui.uibackground, 15) + "50" : darken(ui.uibackground, 15) + "50",
            thumbBorderColor: isDark ? lighten(ui.uibackground, 15) + "50" : darken(ui.uibackground, 15) + "50",
            hoverThumbColor: isDark ? lighten(ui.uibackground, 25) + "80" : darken(ui.uibackground, 25) + "80",
            hoverThumbBorderColor: isDark ? lighten(ui.uibackground, 25) + "80" : darken(ui.uibackground, 25) + "80",
          },
        },
        thumbColor: isDark ? lighten(ui.uibackground, 15) + "80" : darken(ui.uibackground, 15) + "80",
        thumbBorderColor: isDark ? lighten(ui.uibackground, 15) + "80" : darken(ui.uibackground, 15) + "80",
        hoverThumbColor: isDark ? lighten(ui.uibackground, 25) + "B0" : darken(ui.uibackground, 25) + "B0",
        hoverThumbBorderColor: isDark ? lighten(ui.uibackground, 25) + "B0" : darken(ui.uibackground, 25) + "B0",
        trackColor: "transparent",
        hoverTrackColor: isDark ? lighten(ui.uibackground, 5) + "40" : darken(ui.uibackground, 5) + "40",
        Transparent: {
          thumbColor: isDark ? lighten(ui.uibackground, 15) + "50" : darken(ui.uibackground, 15) + "50",
          thumbBorderColor: isDark ? lighten(ui.uibackground, 15) + "50" : darken(ui.uibackground, 15) + "50",
          hoverThumbColor: isDark ? lighten(ui.uibackground, 25) + "80" : darken(ui.uibackground, 25) + "80",
          hoverThumbBorderColor: isDark ? lighten(ui.uibackground, 25) + "80" : darken(ui.uibackground, 25) + "80",
        },
      },
      SearchEverywhere: {
        Advertiser: {
          background: ui.uibackgroundalt,
          foreground: ui.fontalt,
          borderColor: ui.border,
        },
        Header: {
          background: ui.uibackground,
        },
        SearchField: {
          background: ui.uibackground,
          borderColor: ui.border,
        },
        Tab: {
          selectedBackground: ui.defaultalt,
          selectedForeground: ui.font,
        },
      },
      SidePanel: {
        background: ui.uibackgroundalt,
      },
      SpeedSearch: {
        background: ui.uibackgroundalt,
        foreground: ui.font,
        borderColor: ui.primary,
        errorForeground: levels.danger,
      },
      StatusBar: {
        background: frameBackground,
        foreground: ui.fontalt,
        borderColor: transparent,
        hoverBackground: ui.defaultalt,
      },
      TabbedPane: {
        background: ui.uibackground,
        foreground: ui.font,
        contentAreaColor: ui.border,
        hoverColor: ui.defaultalt,
        underlineColor: ui.primary,
        focusColor: ui.defaultalt,
      },
      Table: {
        background: ui.uibackground,
        foreground: ui.font,
        selectionBackground: ui.defaultalt,
        selectionForeground: ui.font,
        selectionInactiveBackground: ui.default,
        selectionInactiveForeground: ui.font,
        gridColor: ui.border,
        hoverBackground: ui.default,
        hoverInactiveBackground: ui.default,
        lightSelectionBackground: ui.defaultalt,
        lightSelectionForeground: ui.font,
        lightSelectionInactiveBackground: ui.default,
        lightSelectionInactiveForeground: ui.font,
        stripeColor: ui.uibackgroundalt,
      },
      TextArea: {
        background: ui.uibackground,
        foreground: ui.font,
        caretForeground: ui.font,
        selectionBackground: isDark ? lighten(ui.uibackground, 15) : darken(ui.uibackground, 15),
        selectionForeground: ui.font,
      },
      TextField: {
        arc: 10,
        background: ui.uibackgroundalt,
        foreground: ui.font,
        caretForeground: ui.font,
        selectionBackground: isDark ? lighten(ui.uibackground, 15) : darken(ui.uibackground, 15),
        selectionForeground: ui.font,
      },
      TitlePane: {
        background: frameBackground,
        foreground: ui.font,
        inactiveBackground: frameBackground,
        inactiveForeground: ui.fontalt,
        Button: {
          hoverBackground: ui.defaultalt,
        },
      },
      ToggleButton: {
        onBackground: ui.primary,
        onForeground: accentForeground,
        offBackground: ui.defaultalt,
        offForeground: ui.font,
        buttonColor: "#ffffff",
      },
      ToolBar: {
        background: frameBackground,
        foreground: ui.font,
      },
      ToolWindow: {
        background: ui.uibackground,
        Button: {
          hoverBackground: ui.defaultalt,
          selectedBackground: ui.defaultalt,
          selectedForeground: ui.font,
        },
        Header: {
          background: ui.uibackgroundalt,
          inactiveBackground: ui.uibackgroundalt,
          borderColor: ui.border,
        },
        Stripe: {
          background: frameBackground,
          borderColor: transparent,
          hoverBackground: ui.defaultalt,
          selectedBackground: ui.primary,
          selectedForeground: accentForeground,
        },
        HeaderTab: {
          selectedBackground: ui.uibackground,
          selectedInactiveBackground: ui.uibackgroundalt,
          hoverBackground: ui.default,
          hoverInactiveBackground: ui.default,
          underlineColor: ui.primary,
          underlineHeight: 3,
          inactiveUnderlineColor: ui.fontalt,
        },
      },
      Tree: {
        background: ui.uibackground,
        foreground: ui.font,
        selectionBackground: ui.defaultalt,
        selectionForeground: ui.font,
        selectionInactiveBackground: ui.default,
        selectionInactiveForeground: ui.font,
        hoverBackground: ui.default,
        hoverInactiveBackground: ui.default,
        modifiedItemForeground: levels.info,
        rowHeight: 24,
      },
      VersionControl: {
        Log: {
          Commit: {
            currentBranchBackground: isDark ? lighten(ui.uibackground, 5) : darken(ui.uibackground, 5),
            hoveredBackground: ui.default,
            selectedBackground: ui.defaultalt,
          },
        },
        RefLabel: {
          backgroundBase: ui.defaultalt,
          backgroundBrightness: isDark ? 0.3 : 0.8,
          foreground: ui.font,
        },
      },
      WelcomeScreen: {
        background: ui.uibackground,
        SidePanel: {
          background: ui.uibackgroundalt,
        },
        separatorColor: ui.border,
        Projects: {
          background: ui.uibackground,
          selectionBackground: ui.defaultalt,
          selectionInactiveBackground: ui.default,
          actions: {
            background: ui.defaultalt,
            selectionBackground: isDark ? lighten(ui.defaultalt, 5) : darken(ui.defaultalt, 5),
          },
        },
      },
    },
    icons: {
      ColorPalette: {
        "Actions.Grey": ui.fontalt,
        "Actions.Red": levels.danger,
        "Actions.Yellow": levels.warning,
        "Actions.Green": levels.success,
        "Actions.Blue": levels.info,
        "Actions.GreyInline": ui.fontalt,
        "Actions.GreyInline.Dark": ui.fontalt,
        "Objects.Grey": ui.fontalt,
        "Objects.RedStatus": levels.danger,
        "Objects.Red": levels.danger,
        "Objects.Pink": colors.pink,
        "Objects.Yellow": colors.yellow,
        "Objects.Green": colors.green,
        "Objects.Blue": colors.blue,
        "Objects.Purple": colors.purple,
        "Objects.BlackText": ui.font,
        "Objects.YellowDark": darken(colors.yellow, 10),
        "Objects.GreenAndroid": colors.green,
        "Checkbox.Background.Default": ui.uibackgroundalt,
        "Checkbox.Border.Default": ui.border,
        "Checkbox.Foreground.Selected": accentForeground,
        "Checkbox.Background.Selected": ui.primary,
        "Checkbox.Border.Selected": ui.primary,
        "Checkbox.Background.Disabled": ui.default,
        "Checkbox.Border.Disabled": ui.border,
        "Checkbox.Foreground.Disabled": ui.fontalt,
      },
    },
  };

  return theme;
}


module.exports = { generateThemeJson };
